[2016-10-11 12:38:14,190: INFO/MainProcess] Connected to amqp://nirlendu:**@localhost:5672/vhost
[2016-10-11 12:38:14,202: INFO/MainProcess] mingle: searching for neighbors
[2016-10-11 12:38:15,213: INFO/MainProcess] mingle: all alone
[2016-10-11 12:38:15,220: WARNING/MainProcess] /Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/kombu/pidbox.py:75: UserWarning: A node named celery@Nirlendus-MacBook-Pro.local is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))
[2016-10-11 12:38:15,226: WARNING/MainProcess] celery@Nirlendus-MacBook-Pro.local ready.
[2016-10-11 12:38:36,065: INFO/MainProcess] Received task: app_base.views.celery_test[77c84e7c-9f14-44f7-9c5a-9df9db11eba0]
[2016-10-11 12:38:36,069: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:38:36,070: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:38:36,112: INFO/MainProcess] Task app_base.views.celery_test[77c84e7c-9f14-44f7-9c5a-9df9db11eba0] succeeded in 0.0445845239992s: None
[2016-10-11 12:38:46,062: INFO/MainProcess] Received task: app_base.views.celery_test[0b00b986-0ee7-4ab1-bc28-c4a750575d81]
[2016-10-11 12:38:46,064: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:38:46,064: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:38:46,110: INFO/MainProcess] Task app_base.views.celery_test[0b00b986-0ee7-4ab1-bc28-c4a750575d81] succeeded in 0.0465115730003s: None
[2016-10-11 12:41:17,237: INFO/MainProcess] Received task: app_base.tasks.add[9a1ddbd4-fde3-40ac-91aa-13d901c03ad8]
[2016-10-11 12:41:17,238: INFO/MainProcess] Received task: app_base.tasks.add[3386af4e-ca4b-492e-b77b-7f4f7dea48c8]
[2016-10-11 12:41:17,239: INFO/MainProcess] Received task: app_base.tasks.add[39e987b6-4a9f-4dfa-8dab-bb8393bd199d]
[2016-10-11 12:41:17,239: INFO/MainProcess] Received task: app_base.tasks.add[3b3cea12-80a6-4706-9208-950f38242c8a]
[2016-10-11 12:41:17,240: INFO/MainProcess] Received task: app_base.views.celery_test[319350d1-33c1-4967-bce6-65e7eeb1686b]
[2016-10-11 12:41:17,240: INFO/MainProcess] Received task: app_base.views.celery_test[2577d2e6-fde4-4503-870a-34b425c42de4]
[2016-10-11 12:41:17,240: INFO/MainProcess] Received task: app_base.views.celery_test[87f428ea-e599-435b-b7ad-a672555ac252]
[2016-10-11 12:41:17,240: INFO/MainProcess] Received task: app_base.views.celery_test[dcac40ef-4065-4374-8dff-e59d44f66e6a]
[2016-10-11 12:41:17,240: INFO/MainProcess] Received task: app_base.views.celery_test[4f846371-0b22-49b9-b907-4ab83b2c7ca7]
[2016-10-11 12:41:17,241: INFO/MainProcess] Received task: app_base.views.celery_test[45a21025-826d-4041-be65-18fb2893179a]
[2016-10-11 12:41:17,241: INFO/MainProcess] Received task: app_base.views.celery_test[a255ed0d-5e9d-495f-9d13-4cdd31c15689]
[2016-10-11 12:41:17,241: INFO/MainProcess] Received task: app_base.views.celery_test[671b3dfe-5990-4813-990d-e62934baa4f8]
[2016-10-11 12:41:17,241: INFO/MainProcess] Received task: app_base.views.celery_test[6be49875-a41a-4d5c-962a-da283bcb1055]
[2016-10-11 12:41:17,241: INFO/MainProcess] Received task: app_base.views.celery_test[9f764397-85a1-47f0-9317-69152293bfe0]
[2016-10-11 12:41:17,242: INFO/MainProcess] Received task: app_base.views.celery_test[8c130847-1432-4b79-a2bb-7c3575f8edfb]
[2016-10-11 12:41:17,242: INFO/MainProcess] Received task: app_base.views.celery_test[2dea51b3-a15e-4ffb-ab76-ed41f6722502]
[2016-10-11 12:41:17,288: INFO/MainProcess] Task app_base.tasks.add[39e987b6-4a9f-4dfa-8dab-bb8393bd199d] succeeded in 0.0452821790004s: 32
[2016-10-11 12:41:17,299: INFO/MainProcess] Task app_base.tasks.add[3b3cea12-80a6-4706-9208-950f38242c8a] succeeded in 0.0572177270005s: 32
[2016-10-11 12:41:17,315: INFO/MainProcess] Task app_base.tasks.add[3386af4e-ca4b-492e-b77b-7f4f7dea48c8] succeeded in 0.0721480269985s: 32
[2016-10-11 12:41:17,314: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:17,314: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:17,315: INFO/MainProcess] Task app_base.tasks.add[9a1ddbd4-fde3-40ac-91aa-13d901c03ad8] succeeded in 0.0730885080011s: 32
[2016-10-11 12:41:17,315: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,316: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,317: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:17,317: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:17,317: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,317: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,360: INFO/MainProcess] Task app_base.views.celery_test[319350d1-33c1-4967-bce6-65e7eeb1686b] succeeded in 0.046501408s: None
[2016-10-11 12:41:17,362: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:17,362: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,371: INFO/MainProcess] Task app_base.views.celery_test[dcac40ef-4065-4374-8dff-e59d44f66e6a] succeeded in 0.0545726379987s: None
[2016-10-11 12:41:17,372: INFO/MainProcess] Task app_base.views.celery_test[87f428ea-e599-435b-b7ad-a672555ac252] succeeded in 0.0552714839996s: None
[2016-10-11 12:41:17,373: INFO/MainProcess] Task app_base.views.celery_test[2577d2e6-fde4-4503-870a-34b425c42de4] succeeded in 0.0589577209994s: None
[2016-10-11 12:41:17,373: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:17,373: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:17,374: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,374: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:17,374: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,374: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,412: INFO/MainProcess] Task app_base.views.celery_test[4f846371-0b22-49b9-b907-4ab83b2c7ca7] succeeded in 0.0505591830006s: None
[2016-10-11 12:41:17,413: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:17,413: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,426: INFO/MainProcess] Task app_base.views.celery_test[a255ed0d-5e9d-495f-9d13-4cdd31c15689] succeeded in 0.0525572240003s: None
[2016-10-11 12:41:17,427: INFO/MainProcess] Task app_base.views.celery_test[45a21025-826d-4041-be65-18fb2893179a] succeeded in 0.0535898500002s: None
[2016-10-11 12:41:17,428: INFO/MainProcess] Task app_base.views.celery_test[671b3dfe-5990-4813-990d-e62934baa4f8] succeeded in 0.0542565939995s: None
[2016-10-11 12:41:17,429: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:17,429: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:17,429: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:17,429: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,429: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,429: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:17,468: INFO/MainProcess] Task app_base.views.celery_test[6be49875-a41a-4d5c-962a-da283bcb1055] succeeded in 0.0548081880006s: None
[2016-10-11 12:41:17,479: INFO/MainProcess] Task app_base.views.celery_test[8c130847-1432-4b79-a2bb-7c3575f8edfb] succeeded in 0.0508514840003s: None
[2016-10-11 12:41:17,480: INFO/MainProcess] Task app_base.views.celery_test[9f764397-85a1-47f0-9317-69152293bfe0] succeeded in 0.0516273900012s: None
[2016-10-11 12:41:17,481: INFO/MainProcess] Task app_base.views.celery_test[2dea51b3-a15e-4ffb-ab76-ed41f6722502] succeeded in 0.0520085709995s: None
[2016-10-11 12:41:21,240: INFO/MainProcess] Received task: app_base.tasks.add[670dc14f-194a-4141-b43c-ded2bbc09545]
[2016-10-11 12:41:21,240: INFO/MainProcess] Received task: app_base.tasks.add[4755ccb6-de34-4308-891a-a38fb3b23d71]
[2016-10-11 12:41:21,241: INFO/MainProcess] Received task: app_base.tasks.add[69fe7d16-c60d-4d6f-bc16-9a1c4c0ef5dc]
[2016-10-11 12:41:21,242: INFO/MainProcess] Received task: app_base.views.celery_test[55a4a96f-24c3-44ca-9a93-44e27d5e2f43]
[2016-10-11 12:41:21,242: INFO/MainProcess] Received task: app_base.views.celery_test[f2a2d538-7abd-48db-b70b-ffbadd06fada]
[2016-10-11 12:41:21,242: INFO/MainProcess] Received task: app_base.views.celery_test[18263886-60a0-4f16-8668-18e4659994a2]
[2016-10-11 12:41:21,243: INFO/MainProcess] Received task: app_base.views.celery_test[582e76f7-fae6-4b8d-8776-02461c75aa1e]
[2016-10-11 12:41:21,243: INFO/MainProcess] Received task: app_base.views.celery_test[24f00eaf-a8d1-4024-9bfb-de795364a457]
[2016-10-11 12:41:21,243: INFO/MainProcess] Received task: app_base.views.celery_test[f79b156f-a550-41a4-bb2a-17578e71f4bc]
[2016-10-11 12:41:21,244: INFO/MainProcess] Received task: app_base.views.celery_test[9744f268-5fb7-4e0f-b000-d1d4373b3fcd]
[2016-10-11 12:41:21,244: INFO/MainProcess] Received task: app_base.views.celery_test[8f8848aa-58f3-45d9-89a8-c7b56c0cbd2c]
[2016-10-11 12:41:21,244: INFO/MainProcess] Received task: app_base.views.celery_test[8948a0b1-9949-4663-a76e-277bbf188f89]
[2016-10-11 12:41:21,244: INFO/MainProcess] Received task: app_base.views.celery_test[b3b3d8f8-5508-4279-a8dc-aced1f2543c8]
[2016-10-11 12:41:21,245: INFO/MainProcess] Received task: app_base.views.celery_test[8e26f467-5ec7-4d22-b9b7-43d94197eebc]
[2016-10-11 12:41:21,245: INFO/MainProcess] Received task: app_base.views.celery_test[94593dbd-312c-422b-a29d-6cf3448027c5]
[2016-10-11 12:41:21,245: INFO/MainProcess] Received task: app_base.views.celery_test[4171896b-d076-4f7b-92bd-8027a30bc075]
[2016-10-11 12:41:21,246: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:21,246: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,286: INFO/MainProcess] Task app_base.tasks.add[4755ccb6-de34-4308-891a-a38fb3b23d71] succeeded in 0.040383607s: 32
[2016-10-11 12:41:21,298: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:21,298: INFO/MainProcess] Task app_base.tasks.add[69fe7d16-c60d-4d6f-bc16-9a1c4c0ef5dc] succeeded in 0.0517844160004s: 32
[2016-10-11 12:41:21,298: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,299: INFO/MainProcess] Task app_base.views.celery_test[55a4a96f-24c3-44ca-9a93-44e27d5e2f43] succeeded in 0.0524360050003s: None
[2016-10-11 12:41:21,299: INFO/MainProcess] Task app_base.tasks.add[670dc14f-194a-4141-b43c-ded2bbc09545] succeeded in 0.0538077760011s: 32
[2016-10-11 12:41:21,301: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:21,301: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,301: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:21,301: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:21,301: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,301: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,347: INFO/MainProcess] Task app_base.views.celery_test[f2a2d538-7abd-48db-b70b-ffbadd06fada] succeeded in 0.0497142099994s: None
[2016-10-11 12:41:21,348: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:21,349: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,359: INFO/MainProcess] Task app_base.views.celery_test[582e76f7-fae6-4b8d-8776-02461c75aa1e] succeeded in 0.0583053790015s: None
[2016-10-11 12:41:21,360: INFO/MainProcess] Task app_base.views.celery_test[18263886-60a0-4f16-8668-18e4659994a2] succeeded in 0.0596651769993s: None
[2016-10-11 12:41:21,361: INFO/MainProcess] Task app_base.views.celery_test[24f00eaf-a8d1-4024-9bfb-de795364a457] succeeded in 0.0599972370001s: None
[2016-10-11 12:41:21,362: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:21,362: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:21,362: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,362: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,396: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:21,396: INFO/MainProcess] Task app_base.views.celery_test[f79b156f-a550-41a4-bb2a-17578e71f4bc] succeeded in 0.048599583999s: None
[2016-10-11 12:41:21,397: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,409: INFO/MainProcess] Task app_base.views.celery_test[8f8848aa-58f3-45d9-89a8-c7b56c0cbd2c] succeeded in 0.047653216001s: None
[2016-10-11 12:41:21,410: INFO/MainProcess] Task app_base.views.celery_test[8948a0b1-9949-4663-a76e-277bbf188f89] succeeded in 0.0485031429998s: None
[2016-10-11 12:41:21,412: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 12:41:21,412: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 12:41:21,412: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,412: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,452: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 12:41:21,453: INFO/MainProcess] Task app_base.views.celery_test[9744f268-5fb7-4e0f-b000-d1d4373b3fcd] succeeded in 0.056612462s: None
[2016-10-11 12:41:21,453: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,454: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 12:41:21,455: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 12:41:21,468: INFO/MainProcess] Task app_base.views.celery_test[8e26f467-5ec7-4d22-b9b7-43d94197eebc] succeeded in 0.056794361999s: None
[2016-10-11 12:41:21,469: INFO/MainProcess] Task app_base.views.celery_test[94593dbd-312c-422b-a29d-6cf3448027c5] succeeded in 0.0574020679996s: None
[2016-10-11 12:41:21,499: INFO/MainProcess] Task app_base.views.celery_test[4171896b-d076-4f7b-92bd-8027a30bc075] succeeded in 0.0453778800002s: None
[2016-10-11 12:41:21,513: INFO/MainProcess] Task app_base.views.celery_test[b3b3d8f8-5508-4279-a8dc-aced1f2543c8] succeeded in 0.0607627419995s: None
[2016-10-11 13:09:14,380: INFO/MainProcess] Received task: app_base.tasks.add[ed075402-5a2b-4937-bfd2-0096500e7433]
[2016-10-11 13:09:14,381: INFO/MainProcess] Received task: app_base.tasks.add[685869aa-b2d4-413d-aed3-0e47b0e7685c]
[2016-10-11 13:09:14,381: INFO/MainProcess] Received task: app_base.tasks.add[2676f506-c941-4baf-8768-6c21c1e88395]
[2016-10-11 13:09:14,382: INFO/MainProcess] Received task: app_base.views.celery_test[61a604f3-9eca-4dee-ae8a-03e17789fa63]
[2016-10-11 13:09:14,382: INFO/MainProcess] Received task: app_base.views.celery_test[71fd9a84-e4ec-4c24-b1fc-d53a0acdaa63]
[2016-10-11 13:09:14,383: INFO/MainProcess] Received task: app_base.views.celery_test[9a5a5fd6-001b-41b6-a3e9-cd9ad2526931]
[2016-10-11 13:09:14,383: INFO/MainProcess] Received task: app_base.views.celery_test[c8afa9af-d651-4382-8fb6-e1ade779715d]
[2016-10-11 13:09:14,383: INFO/MainProcess] Received task: app_base.views.celery_test[b3330f89-9bd2-4957-8262-402a29e6f2dc]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[ce4d77ce-4d1d-42bd-8fc8-7ef00a273e3c]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[3c33ac32-c27e-4b56-9f9e-0dfd9b829dd4]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[093b1e2b-458b-4c87-9899-68eafcf92db3]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[02bd5ea4-caaa-4b21-8200-d681616ae686]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[95ceef33-d0ba-4dc3-9aae-0e48e3de59fa]
[2016-10-11 13:09:14,384: INFO/MainProcess] Received task: app_base.views.celery_test[9532d9e7-7c0b-4372-96c5-0186f63028df]
[2016-10-11 13:09:14,385: INFO/MainProcess] Received task: app_base.views.celery_test[3950229d-ff9c-465a-bbfc-e16652528923]
[2016-10-11 13:09:14,385: INFO/MainProcess] Received task: app_base.views.celery_test[df3f0945-d717-4d07-a768-fd97728348d6]
[2016-10-11 13:09:14,385: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:09:14,386: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,429: INFO/MainProcess] Task app_base.views.celery_test[61a604f3-9eca-4dee-ae8a-03e17789fa63] succeeded in 0.0432420969992s: None
[2016-10-11 13:09:14,440: INFO/MainProcess] Task app_base.tasks.add[2676f506-c941-4baf-8768-6c21c1e88395] succeeded in 0.0552106200012s: 32
[2016-10-11 13:09:14,442: INFO/MainProcess] Task app_base.tasks.add[ed075402-5a2b-4937-bfd2-0096500e7433] succeeded in 0.0563242209992s: 32
[2016-10-11 13:09:14,441: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:09:14,443: INFO/MainProcess] Task app_base.tasks.add[685869aa-b2d4-413d-aed3-0e47b0e7685c] succeeded in 0.057102757999s: 32
[2016-10-11 13:09:14,442: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,444: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:09:14,444: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:09:14,444: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:09:14,444: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,444: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,444: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,482: INFO/MainProcess] Task app_base.views.celery_test[71fd9a84-e4ec-4c24-b1fc-d53a0acdaa63] succeeded in 0.0412394700015s: None
[2016-10-11 13:09:14,483: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:09:14,483: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,493: INFO/MainProcess] Task app_base.views.celery_test[b3330f89-9bd2-4957-8262-402a29e6f2dc] succeeded in 0.0494009209997s: None
[2016-10-11 13:09:14,494: INFO/MainProcess] Task app_base.views.celery_test[9a5a5fd6-001b-41b6-a3e9-cd9ad2526931] succeeded in 0.0502766779991s: None
[2016-10-11 13:09:14,494: INFO/MainProcess] Task app_base.views.celery_test[c8afa9af-d651-4382-8fb6-e1ade779715d] succeeded in 0.0505878100012s: None
[2016-10-11 13:09:14,495: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:09:14,495: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:09:14,495: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,495: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,495: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:09:14,496: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,530: INFO/MainProcess] Task app_base.views.celery_test[ce4d77ce-4d1d-42bd-8fc8-7ef00a273e3c] succeeded in 0.0472867530007s: None
[2016-10-11 13:09:14,531: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:09:14,532: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,542: INFO/MainProcess] Task app_base.views.celery_test[093b1e2b-458b-4c87-9899-68eafcf92db3] succeeded in 0.0469514190008s: None
[2016-10-11 13:09:14,543: INFO/MainProcess] Task app_base.views.celery_test[02bd5ea4-caaa-4b21-8200-d681616ae686] succeeded in 0.0480346980003s: None
[2016-10-11 13:09:14,544: INFO/MainProcess] Task app_base.views.celery_test[3c33ac32-c27e-4b56-9f9e-0dfd9b829dd4] succeeded in 0.049225625s: None
[2016-10-11 13:09:14,545: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:09:14,545: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:09:14,545: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:09:14,545: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,545: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,545: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:09:14,578: INFO/MainProcess] Task app_base.views.celery_test[95ceef33-d0ba-4dc3-9aae-0e48e3de59fa] succeeded in 0.0473036780004s: None
[2016-10-11 13:09:14,594: INFO/MainProcess] Task app_base.views.celery_test[3950229d-ff9c-465a-bbfc-e16652528923] succeeded in 0.0497475129996s: None
[2016-10-11 13:09:14,595: INFO/MainProcess] Task app_base.views.celery_test[9532d9e7-7c0b-4372-96c5-0186f63028df] succeeded in 0.0503619430001s: None
[2016-10-11 13:09:14,595: INFO/MainProcess] Task app_base.views.celery_test[df3f0945-d717-4d07-a768-fd97728348d6] succeeded in 0.0504470989999s: None
[2016-10-11 13:10:00,451: INFO/MainProcess] Received task: app_base.tasks.add[84984028-b5f6-42f0-8c66-24f2d7fd16a7]
[2016-10-11 13:10:00,452: INFO/MainProcess] Received task: app_base.tasks.add[508c5f8b-1271-4e76-8869-0458d5af339b]
[2016-10-11 13:10:00,453: INFO/MainProcess] Received task: app_base.tasks.add[61c14135-d9ac-44a6-898e-54832aeee194]
[2016-10-11 13:10:00,454: INFO/MainProcess] Received task: app_base.views.celery_test[19942ca4-5070-4134-a3ea-852458515ec3]
[2016-10-11 13:10:00,454: INFO/MainProcess] Received task: app_base.views.celery_test[bd35508b-ab47-4ddf-9e65-fe096207af88]
[2016-10-11 13:10:00,455: INFO/MainProcess] Received task: app_base.views.celery_test[027e2a5c-f846-4568-8ba6-577f4ca1f20b]
[2016-10-11 13:10:00,455: INFO/MainProcess] Received task: app_base.views.celery_test[060f1624-6b04-47d5-bb7b-edd58726a4a8]
[2016-10-11 13:10:00,455: INFO/MainProcess] Received task: app_base.views.celery_test[b45c43ef-4f57-442a-8040-f5e7ef9410c0]
[2016-10-11 13:10:00,455: INFO/MainProcess] Received task: app_base.views.celery_test[3ff25750-a9ab-467f-85c7-2591da46f4b9]
[2016-10-11 13:10:00,456: INFO/MainProcess] Received task: app_base.views.celery_test[389274bc-fff7-44ef-b302-83e1347ad8ca]
[2016-10-11 13:10:00,456: INFO/MainProcess] Received task: app_base.views.celery_test[854a2314-8dd1-4109-80d4-dbd1bd21bfa6]
[2016-10-11 13:10:00,456: INFO/MainProcess] Received task: app_base.views.celery_test[c501cab8-b52a-44b7-83da-2584a81c5452]
[2016-10-11 13:10:00,457: INFO/MainProcess] Received task: app_base.views.celery_test[ac2cb6fc-8485-4c88-9585-28dd45792bae]
[2016-10-11 13:10:00,457: INFO/MainProcess] Received task: app_base.views.celery_test[ae04b69b-adc9-445c-a0fd-14675bb1c31d]
[2016-10-11 13:10:00,457: INFO/MainProcess] Received task: app_base.views.celery_test[85b46d55-c2d0-4be2-9721-cb10b7d33934]
[2016-10-11 13:10:00,457: INFO/MainProcess] Received task: app_base.views.celery_test[f497312b-42bc-4698-8eac-98ef290cff6f]
[2016-10-11 13:10:00,459: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:00,459: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,497: INFO/MainProcess] Task app_base.tasks.add[84984028-b5f6-42f0-8c66-24f2d7fd16a7] succeeded in 0.0391696409988s: 32
[2016-10-11 13:10:00,498: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:00,498: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,509: INFO/MainProcess] Task app_base.tasks.add[61c14135-d9ac-44a6-898e-54832aeee194] succeeded in 0.0502806369987s: 32
[2016-10-11 13:10:00,509: INFO/MainProcess] Task app_base.tasks.add[508c5f8b-1271-4e76-8869-0458d5af339b] succeeded in 0.0514057609998s: 32
[2016-10-11 13:10:00,510: INFO/MainProcess] Task app_base.views.celery_test[19942ca4-5070-4134-a3ea-852458515ec3] succeeded in 0.0515048840007s: None
[2016-10-11 13:10:00,511: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:00,511: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:00,512: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,511: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,511: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:00,513: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,541: INFO/MainProcess] Task app_base.views.celery_test[bd35508b-ab47-4ddf-9e65-fe096207af88] succeeded in 0.0431021610002s: None
[2016-10-11 13:10:00,542: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:00,542: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,552: INFO/MainProcess] Task app_base.views.celery_test[027e2a5c-f846-4568-8ba6-577f4ca1f20b] succeeded in 0.0416988739998s: None
[2016-10-11 13:10:00,553: INFO/MainProcess] Task app_base.views.celery_test[b45c43ef-4f57-442a-8040-f5e7ef9410c0] succeeded in 0.0418905919996s: None
[2016-10-11 13:10:00,554: INFO/MainProcess] Task app_base.views.celery_test[060f1624-6b04-47d5-bb7b-edd58726a4a8] succeeded in 0.0430279089996s: None
[2016-10-11 13:10:00,554: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:00,555: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:00,555: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,555: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,555: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:00,555: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,592: INFO/MainProcess] Task app_base.views.celery_test[3ff25750-a9ab-467f-85c7-2591da46f4b9] succeeded in 0.0505652449992s: None
[2016-10-11 13:10:00,593: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:00,593: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,606: INFO/MainProcess] Task app_base.views.celery_test[854a2314-8dd1-4109-80d4-dbd1bd21bfa6] succeeded in 0.0521526800003s: None
[2016-10-11 13:10:00,607: INFO/MainProcess] Task app_base.views.celery_test[389274bc-fff7-44ef-b302-83e1347ad8ca] succeeded in 0.0530494400009s: None
[2016-10-11 13:10:00,608: INFO/MainProcess] Task app_base.views.celery_test[c501cab8-b52a-44b7-83da-2584a81c5452] succeeded in 0.0531506360003s: None
[2016-10-11 13:10:00,609: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:00,609: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:00,609: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:00,609: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,609: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,609: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:00,645: INFO/MainProcess] Task app_base.views.celery_test[ac2cb6fc-8485-4c88-9585-28dd45792bae] succeeded in 0.0525660929998s: None
[2016-10-11 13:10:00,657: INFO/MainProcess] Task app_base.views.celery_test[85b46d55-c2d0-4be2-9721-cb10b7d33934] succeeded in 0.0482919810001s: None
[2016-10-11 13:10:00,658: INFO/MainProcess] Task app_base.views.celery_test[ae04b69b-adc9-445c-a0fd-14675bb1c31d] succeeded in 0.0489697169996s: None
[2016-10-11 13:10:00,658: INFO/MainProcess] Task app_base.views.celery_test[f497312b-42bc-4698-8eac-98ef290cff6f] succeeded in 0.0493932900008s: None
[2016-10-11 13:10:18,480: INFO/MainProcess] Received task: app_base.views.celery_test[877312cd-0c75-471b-a0ab-5463f34ba315]
[2016-10-11 13:10:18,482: INFO/MainProcess] Received task: app_base.views.celery_test[bae5d13d-b8eb-4629-b7ff-6f0620b1c263]
[2016-10-11 13:10:18,482: INFO/MainProcess] Received task: app_base.views.celery_test[8dd7a766-538b-4156-b97a-2eb48d7c0faf]
[2016-10-11 13:10:18,483: INFO/MainProcess] Received task: app_base.views.celery_test[f8299085-9d00-4d68-95f8-b17079934bf0]
[2016-10-11 13:10:18,483: INFO/MainProcess] Received task: app_base.views.celery_test[28771e35-f9b7-4217-a4c6-068490c34719]
[2016-10-11 13:10:18,484: INFO/MainProcess] Received task: app_base.views.celery_test[a9653b55-adc2-48d2-bb6f-7c97fe1cbe48]
[2016-10-11 13:10:18,484: INFO/MainProcess] Received task: app_base.views.celery_test[9ee99f24-c4f5-4990-bf9d-ab12692b0588]
[2016-10-11 13:10:18,484: INFO/MainProcess] Received task: app_base.views.celery_test[2aadd945-18c9-45d2-ad71-bbe7695cdbc2]
[2016-10-11 13:10:18,485: INFO/MainProcess] Received task: app_base.views.celery_test[37a35414-04b9-4ab9-856d-a9c182f97abf]
[2016-10-11 13:10:18,485: INFO/MainProcess] Received task: app_base.views.celery_test[cdbe1222-94cd-48bb-ae52-5e2d01d37e52]
[2016-10-11 13:10:18,485: INFO/MainProcess] Received task: app_base.views.celery_test[e1355065-6cc3-4b2b-9466-3dd96e03ad65]
[2016-10-11 13:10:18,486: INFO/MainProcess] Received task: app_base.views.celery_test[9698e203-05af-43be-b3e2-ab5c067073bb]
[2016-10-11 13:10:18,486: INFO/MainProcess] Received task: app_base.views.celery_test[0b8c778d-0b21-445c-8fe0-6e0fc06a9469]
[2016-10-11 13:10:18,486: INFO/MainProcess] Received task: app_base.views.celery_test[8f23e097-7f5f-46aa-8854-3ed38b8e6fed]
[2016-10-11 13:10:18,487: INFO/MainProcess] Received task: app_base.views.celery_test[5d9d6931-7203-4d17-b80b-eabd509e67f7]
[2016-10-11 13:10:18,487: INFO/MainProcess] Received task: app_base.views.celery_test[61995da0-deaf-4aa1-b1d0-d8cd941a063c]
[2016-10-11 13:10:18,488: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:18,488: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:18,488: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,488: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:18,489: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,489: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,489: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:18,490: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,535: INFO/MainProcess] Task app_base.views.celery_test[8dd7a766-538b-4156-b97a-2eb48d7c0faf] succeeded in 0.0466045880003s: None
[2016-10-11 13:10:18,536: INFO/MainProcess] Task app_base.views.celery_test[877312cd-0c75-471b-a0ab-5463f34ba315] succeeded in 0.0482330529994s: None
[2016-10-11 13:10:18,537: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:18,537: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,546: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:18,547: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,548: INFO/MainProcess] Task app_base.views.celery_test[bae5d13d-b8eb-4629-b7ff-6f0620b1c263] succeeded in 0.059530763001s: None
[2016-10-11 13:10:18,548: INFO/MainProcess] Task app_base.views.celery_test[f8299085-9d00-4d68-95f8-b17079934bf0] succeeded in 0.0592335170004s: None
[2016-10-11 13:10:18,549: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:18,549: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:18,550: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,550: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,583: INFO/MainProcess] Task app_base.views.celery_test[28771e35-f9b7-4217-a4c6-068490c34719] succeeded in 0.0466992339989s: None
[2016-10-11 13:10:18,585: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:18,586: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,597: INFO/MainProcess] Task app_base.views.celery_test[9ee99f24-c4f5-4990-bf9d-ab12692b0588] succeeded in 0.0476005679993s: None
[2016-10-11 13:10:18,597: INFO/MainProcess] Task app_base.views.celery_test[a9653b55-adc2-48d2-bb6f-7c97fe1cbe48] succeeded in 0.0510343549995s: None
[2016-10-11 13:10:18,598: INFO/MainProcess] Task app_base.views.celery_test[2aadd945-18c9-45d2-ad71-bbe7695cdbc2] succeeded in 0.0487882329999s: None
[2016-10-11 13:10:18,599: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:18,599: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:18,599: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,599: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,640: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:18,640: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,641: INFO/MainProcess] Task app_base.views.celery_test[37a35414-04b9-4ab9-856d-a9c182f97abf] succeeded in 0.0557796159992s: None
[2016-10-11 13:10:18,652: INFO/MainProcess] Task app_base.views.celery_test[e1355065-6cc3-4b2b-9466-3dd96e03ad65] succeeded in 0.0534435610007s: None
[2016-10-11 13:10:18,653: INFO/MainProcess] Task app_base.views.celery_test[9698e203-05af-43be-b3e2-ab5c067073bb] succeeded in 0.0544200240001s: None
[2016-10-11 13:10:18,654: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:18,654: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:18,654: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,655: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,694: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:18,694: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,694: INFO/MainProcess] Task app_base.views.celery_test[cdbe1222-94cd-48bb-ae52-5e2d01d37e52] succeeded in 0.0542180989996s: None
[2016-10-11 13:10:18,695: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:18,696: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:18,708: INFO/MainProcess] Task app_base.views.celery_test[8f23e097-7f5f-46aa-8854-3ed38b8e6fed] succeeded in 0.0543481690001s: None
[2016-10-11 13:10:18,722: INFO/MainProcess] Task app_base.views.celery_test[5d9d6931-7203-4d17-b80b-eabd509e67f7] succeeded in 0.0681759899999s: None
[2016-10-11 13:10:18,743: INFO/MainProcess] Task app_base.views.celery_test[61995da0-deaf-4aa1-b1d0-d8cd941a063c] succeeded in 0.0483316819991s: None
[2016-10-11 13:10:18,766: INFO/MainProcess] Task app_base.views.celery_test[0b8c778d-0b21-445c-8fe0-6e0fc06a9469] succeeded in 0.0723048030013s: None
[2016-10-11 13:10:20,485: INFO/MainProcess] Received task: app_base.views.celery_test[f02cc3a9-f079-4a88-b432-7b1c1826bb2e]
[2016-10-11 13:10:20,486: INFO/MainProcess] Received task: app_base.views.celery_test[98941bfe-b845-4c8d-8814-46ddb3276e75]
[2016-10-11 13:10:20,487: INFO/MainProcess] Received task: app_base.views.celery_test[cedf8dbc-f31f-447a-b2b8-ea06e29c0cc1]
[2016-10-11 13:10:20,488: INFO/MainProcess] Received task: app_base.views.celery_test[aca3cc1d-e2d3-4f0d-a71b-5490ec3083fd]
[2016-10-11 13:10:20,488: INFO/MainProcess] Received task: app_base.views.celery_test[f8c4c486-0a13-45ae-8ab1-e96ad8faeead]
[2016-10-11 13:10:20,489: INFO/MainProcess] Received task: app_base.views.celery_test[3f767b97-701a-4a20-ba47-603bc354254f]
[2016-10-11 13:10:20,489: INFO/MainProcess] Received task: app_base.views.celery_test[dc6089cc-2c82-42e8-b4ce-d2990aaba55a]
[2016-10-11 13:10:20,489: INFO/MainProcess] Received task: app_base.views.celery_test[63e88fed-867a-4470-b6da-ad44fa99f157]
[2016-10-11 13:10:20,489: INFO/MainProcess] Received task: app_base.views.celery_test[aff1a62b-577f-4d1d-9d81-118a0d6b7942]
[2016-10-11 13:10:20,489: INFO/MainProcess] Received task: app_base.views.celery_test[dc30855f-9dda-4983-9d86-9a8c5cb2c3a1]
[2016-10-11 13:10:20,490: INFO/MainProcess] Received task: app_base.views.celery_test[a1b91de1-6b4d-4330-8984-97472d700131]
[2016-10-11 13:10:20,490: INFO/MainProcess] Received task: app_base.views.celery_test[1943847d-a4f1-4d2e-b2e7-0359549f6faf]
[2016-10-11 13:10:20,490: INFO/MainProcess] Received task: app_base.views.celery_test[6a664b08-47d5-426c-92f9-b3b348b2d684]
[2016-10-11 13:10:20,491: INFO/MainProcess] Received task: app_base.views.celery_test[df168165-4255-4780-b462-5fc2754b20b7]
[2016-10-11 13:10:20,491: INFO/MainProcess] Received task: app_base.views.celery_test[aa6e9895-07de-417f-9d13-6d6e458878b3]
[2016-10-11 13:10:20,491: INFO/MainProcess] Received task: app_base.views.celery_test[365168c5-5f11-4646-ba57-aa61d6499635]
[2016-10-11 13:10:20,492: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:20,492: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:20,492: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,493: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,493: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:20,493: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:20,494: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,494: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,542: INFO/MainProcess] Task app_base.views.celery_test[f02cc3a9-f079-4a88-b432-7b1c1826bb2e] succeeded in 0.0501342450007s: None
[2016-10-11 13:10:20,543: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:20,544: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,555: INFO/MainProcess] Task app_base.views.celery_test[cedf8dbc-f31f-447a-b2b8-ea06e29c0cc1] succeeded in 0.0624072419996s: None
[2016-10-11 13:10:20,556: INFO/MainProcess] Task app_base.views.celery_test[98941bfe-b845-4c8d-8814-46ddb3276e75] succeeded in 0.0639022309988s: None
[2016-10-11 13:10:20,557: INFO/MainProcess] Task app_base.views.celery_test[aca3cc1d-e2d3-4f0d-a71b-5490ec3083fd] succeeded in 0.0637413050008s: None
[2016-10-11 13:10:20,558: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:20,559: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:20,559: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,559: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,601: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:20,601: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,601: INFO/MainProcess] Task app_base.views.celery_test[f8c4c486-0a13-45ae-8ab1-e96ad8faeead] succeeded in 0.058214138s: None
[2016-10-11 13:10:20,617: INFO/MainProcess] Task app_base.views.celery_test[63e88fed-867a-4470-b6da-ad44fa99f157] succeeded in 0.0589022540007s: None
[2016-10-11 13:10:20,620: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:20,621: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,636: INFO/MainProcess] Task app_base.views.celery_test[dc6089cc-2c82-42e8-b4ce-d2990aaba55a] succeeded in 0.0777338999997s: None
[2016-10-11 13:10:20,638: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:20,639: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,670: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:20,670: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,670: INFO/MainProcess] Task app_base.views.celery_test[3f767b97-701a-4a20-ba47-603bc354254f] succeeded in 0.0699269899997s: None
[2016-10-11 13:10:20,672: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:20,672: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,686: INFO/MainProcess] Task app_base.views.celery_test[dc30855f-9dda-4983-9d86-9a8c5cb2c3a1] succeeded in 0.0667552020004s: None
[2016-10-11 13:10:20,700: INFO/MainProcess] Task app_base.views.celery_test[a1b91de1-6b4d-4330-8984-97472d700131] succeeded in 0.0628011049994s: None
[2016-10-11 13:10:20,702: INFO/Worker-3] ########### Celery task started ###########
[2016-10-11 13:10:20,703: WARNING/Worker-3] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,721: INFO/Worker-1] ########### Celery task started ###########
[2016-10-11 13:10:20,721: INFO/MainProcess] Task app_base.views.celery_test[aff1a62b-577f-4d1d-9d81-118a0d6b7942] succeeded in 0.0518819810004s: None
[2016-10-11 13:10:20,721: WARNING/Worker-1] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,724: INFO/Worker-2] ########### Celery task started ###########
[2016-10-11 13:10:20,725: WARNING/Worker-2] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,738: INFO/MainProcess] Task app_base.views.celery_test[1943847d-a4f1-4d2e-b2e7-0359549f6faf] succeeded in 0.0657295420006s: None
[2016-10-11 13:10:20,740: INFO/Worker-4] ########### Celery task started ###########
[2016-10-11 13:10:20,741: WARNING/Worker-4] RUNNING CELERY TASKS! :)
[2016-10-11 13:10:20,771: INFO/MainProcess] Task app_base.views.celery_test[df168165-4255-4780-b462-5fc2754b20b7] succeeded in 0.0691358580007s: None
[2016-10-11 13:10:20,791: INFO/MainProcess] Task app_base.views.celery_test[aa6e9895-07de-417f-9d13-6d6e458878b3] succeeded in 0.0680779590002s: None
[2016-10-11 13:10:20,794: INFO/MainProcess] Task app_base.views.celery_test[6a664b08-47d5-426c-92f9-b3b348b2d684] succeeded in 0.0730381099984s: None
[2016-10-11 13:10:20,807: INFO/MainProcess] Task app_base.views.celery_test[365168c5-5f11-4646-ba57-aa61d6499635] succeeded in 0.0669229759988s: None
[2016-10-11 15:56:24,270: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'379a1e61-922d-4aa1-82f9-3719919e31bd'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:29,269: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'2f1e9f9c-140c-43bb-b80e-6953e5f05670'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:34,269: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'65cb3331-2666-4d65-bc9d-b3bb6c415f62'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:39,269: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'73c99ac7-1560-4355-b5db-8dfaac5541c0'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:44,269: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'f4833b1f-b8c9-4547-a98c-4eb78f7813ce'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:49,269: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'ac882477-dca8-4979-b107-aed9be2bab53'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:56:59,270: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'c119e5ae-3e06-4b55-bcb0-e238c90c07a9'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:57:09,270: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'6985c811-d756-4c27-960c-b4d20f482ecf'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 15:57:14,271: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'148ab382-7754-43bc-b8a3-55d87b6b048d'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:00:42,718: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'5dfdd0ea-6b97-4331-8ad9-0570c1c3abcd'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:00:52,716: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'b396617a-0620-4b8e-8881-0f81cad3ed3c'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:03:33,840: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'21c11051-09c3-4451-b2ba-ccacfd11b2c9'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:03:43,838: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'1c408903-0936-432b-9919-531deb52ed97'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:05:18,843: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'2e81f101-53c4-425b-bc63-bd2e122e244f'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:05:28,842: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'821caf02-7be7-4918-b114-b848c3416d24'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:06:19,899: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'42f1661a-51bd-48b7-92bf-ca6e4505b726'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:08:22,310: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'7bcbbb8c-8be2-4a59-941e-fd6bf2961489'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:08:32,307: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'6adf3d97-f2e7-4a45-8ae7-bb74534ea3ed'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:10:41,684: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'dd6c2e9c-1ccc-4979-90b5-071b6d29505f'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:10:51,682: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'45f29616-322c-46fa-93ae-6fb97660d9c5'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:12:14,044: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'74c7cf4a-46ea-401d-95a4-c08486a6c31f'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:12:24,041: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'03db5ed0-2477-4659-9d7d-58180dab8df2'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:12:34,041: ERROR/MainProcess] Received unregistered task of type u'app_base.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_base.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'0ce2862a-6611-4b25-9eb7-9e979d1b3d59'} (270b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_base.views.update_graph_cache'
[2016-10-11 16:14:55,552: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'0dc33485-8186-4576-858c-e92b24f66add'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:15:05,550: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'71976252-f715-4552-abb9-6df221e3a855'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:16:52,224: ERROR/MainProcess] Received unregistered task of type u'app_core.update_cache.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'app_core.update_cache.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'3995b135-2649-469b-90db-68e68beed4dd'} (277b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'app_core.update_cache.update_graph_cache'
[2016-10-11 16:21:20,132: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'19e40742-5ab6-40ee-b3ae-212070a9376c'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:21:30,130: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'5c66568c-3c93-47ec-a8bf-99f296021633'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:26:30,125: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'ff1d4108-3f84-4be8-81ab-b46b0a9792ec'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:28:01,295: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'f3708910-d9d0-43be-afe3-9812805806c6'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:31:42,917: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'3f5f3854-a4b3-4068-886d-9a9ce099e285'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:31:52,915: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'c7f902e4-e038-43e0-9ff9-2d12760c540d'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
[2016-10-11 16:41:10,501: ERROR/MainProcess] Received unregistered task of type u'cache_operations.views.update_graph_cache'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'cache_operations.views.update_graph_cache', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'4951336b-a6e4-4daf-a213-78876d058aa1'} (278b)
Traceback (most recent call last):
  File "/Users/nirlendu/Documents/Codes/myApp/venv/lib/python2.7/site-packages/celery/worker/consumer.py", line 465, in on_task_received
    strategies[type_](message, body,
KeyError: u'cache_operations.views.update_graph_cache'
